### PR TITLE
new project details "page"

### PR DESCRIPTION
**Pull request by milafrerichs**
Creates a sub"page" for projects to include Name, Description, Link to Github,Demo-Page and some stats

regarding #4

### CODE REVIEW

**Comment by BretFisher** [comment]
interesting idea, we'll take a look, thanks.

**Comment by kmcurry** [comment]
Did we forget about this?

**Comment by milafrerichs** [comment]
@kmcurry seems that way. :)
didn't wanted to bother you guys.

**Comment by qwo** [comment]
moved discussion of project pages to #103

**Pull request closed without merging**
