### PR TITLE
Added My Name

### PR DESCRIPTION
**Pull request by thecbliss**

### CODE REVIEW

**Comment by benkra2802** [comment]
?Blaine,

Please let me know what time you guys are meeting tomorrow and what time.

Thank you

Ben Kramarczuk

757-597-8656

**Comment by qwo** [comment]
I think we're meeting at Stella's tomorrow at 3PM.

http://www.yelp.com/biz/cafe-stella-norfolk

**Comment by wbprice** [comment]
See also:
http://openhealthinspection.com/#/vendor/cafe-stella-1907-colonial-avenue

**Comment by BretFisher** [comment]
That doesn't work for me, just takes to home page with listing on mac
safari.

**Pull request merged**
